from sqlmodel import SQLModel, Field
from sqlalchemy import Column, Integer, String, Boolean, DateTime, DECIMAL
from typing import Optional
from datetime import datetime

class Store(SQLModel, table=True):

    storecode: Optional[str] = Field(default="", sa_column=Column("StoreCode", String))
    name: Optional[str] = Field(default="", sa_column=Column("Name", String))
    name2: Optional[str] = Field(default="", sa_column=Column("Name2", String))
    storelocationcode: Optional[str] = Field(default="", sa_column=Column("StoreLocationCode", String))
    lookupcode: Optional[str] = Field(default="", sa_column=Column("LookUpCode", String))
    customerid: Optional[int] = Field(default=-1, sa_column=Column("CustomerId", Integer))
    customercompanyid: Optional[int] = Field(default=-1, sa_column=Column("CustomerCompanyId", Integer))
    customersiteid: Optional[int] = Field(default=-1, sa_column=Column("CustomerSiteId", Integer))
    companyid: Optional[int] = Field(default=-1, sa_column=Column("CompanyId", Integer))
    brandid: Optional[int] = Field(default=-1, sa_column=Column("BrandId", Integer))
    storetypeid: Optional[int] = Field(default=-1, sa_column=Column("StoreTypeId", Integer))
    countryid: Optional[int] = Field(default=-1, sa_column=Column("CountryId", Integer))
    currencyid: Optional[int] = Field(default=-1, sa_column=Column("CurrencyId", Integer))
    contactperson: Optional[str] = Field(default="", sa_column=Column("ContactPerson", String))
    address: Optional[str] = Field(default="", sa_column=Column("Address", String))
    address2: Optional[str] = Field(default="", sa_column=Column("Address2", String))
    postalcode: Optional[str] = Field(default="", sa_column=Column("PostalCode", String))
    phonenumber: Optional[str] = Field(default="", sa_column=Column("PhoneNumber", String))
    faxnumber: Optional[str] = Field(default="", sa_column=Column("FaxNumber", String))
    emailaddress: Optional[str] = Field(default="", sa_column=Column("EmailAddress", String))
    homepageaddress: Optional[str] = Field(default="", sa_column=Column("HomePageAddress", String))
    customerpostinggroupid: Optional[int] = Field(default=-1, sa_column=Column("CustomerPostingGroupId", Integer))
    generalpostinggroupid: Optional[int] = Field(default=-1, sa_column=Column("GeneralPostingGroupId", Integer))
    paymenttermsid: Optional[int] = Field(default=-1, sa_column=Column("PaymentTermsId", Integer))
    paymentmethodid: Optional[int] = Field(default=-1, sa_column=Column("PaymentMethodId", Integer))
    paymentapplicationmethodid: Optional[int] = Field(default=-1, sa_column=Column("PaymentApplicationMethodId", Integer))
    tin: Optional[str] = Field(default="", sa_column=Column("TIN", String))
    whtpostinggroupid: Optional[int] = Field(default=-1, sa_column=Column("WhtPostingGroupId", Integer))
    vatpostinggroupid: int = Field(default=-1, sa_column=Column("VatPostingGroupId", Integer))
    globaldimensionid1: Optional[int] = Field(default=-1, sa_column=Column("GlobalDimensionId1", Integer))
    globaldimensionid2: Optional[int] = Field(default=-1, sa_column=Column("GlobalDimensionId2", Integer))
    prepaymentpercent: Optional[float] = Field(default=0, sa_column=Column("PrePaymentPercent", DECIMAL))
    shippingadviceid: Optional[int] = Field(default=-1, sa_column=Column("ShippingAdviceId", Integer))
    allowlinediscount: Optional[bool] = Field(default=False, sa_column=Column("AllowLineDiscount", Boolean))
    remark: Optional[str] = Field(default="", sa_column=Column("Remark", String))
    isactive: Optional[bool] = Field(default=True, sa_column=Column("IsActive", Boolean))
    createby: Optional[str] = Field(default="", sa_column=Column("CreateBy", String))
    createdate: datetime = Field(default_factory=datetime.now, sa_column=Column("CreateDate", DateTime))
    updateby: Optional[str] = Field(default="", sa_column=Column("UpdateBy", String))
    updatedate: Optional[datetime] = Field(default_factory=datetime.now, sa_column=Column("UpdateDate", DateTime))
